config/routes.rb
Rails.application.routes.draw do
  mount Exposition::Engine, at: "/"
  namespace :admin do
    resources :book_reviews
    resources :tools
  end

  resources :book_reviews, only: [:index]
  resources :tools, only: [:index]

  # Mapping high voltage to custom controller
  get "/pages/*id" => 'pages#show', as: :page, format: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_review.rb
class BookReview < ActiveRecord::Base
  include Authorable
  include HumanUrls::Sluggable
  include Publishable
  include Categorical::Taggable

  validates_presence_of :book_title, :body, :book_author
  validates_length_of :book_title, :book_author, maximum: 244

  sluggify :slug, generated_from: :book_title
end

app/models/categorical/tag.rb
class Categorical::Tag < ActiveRecord::Base
  include Categorical::Concerns::Models::Tag
  include HumanUrls::Sluggable

  sluggify :slug, generated_from: :label
end

app/models/concerns/authorable.rb
module Authorable
  extend ActiveSupport::Concern

  included do
    belongs_to :author, class_name: 'Exposition::User'
    validates_presence_of :author
  end
end

app/models/concerns/publishable.rb
module Publishable
  extend ActiveSupport::Concern

  included do
    before_save :set_published_at_date
  end

  def css_classes
    if published?
      return "published"
    else
      return "not-published"
    end
  end

  private

  def set_published_at_date
    if published_changed?(from: false, to: true)
      self.published_at = Date.today
    end
  end

  module ClassMethods
    def published
      where(published: true)
    end

    def sorted_by_published_date
      order(published_at: :desc)
    end
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  include HumanUrls::Sluggable
  include Publishable
  include Categorical::Taggable

  validates_presence_of :title, :body
  validates_length_of :title, maximum: 244

  sluggify :slug, generated_from: :title
end

app/controllers/admin/book_reviews_controller.rb
class Admin::BookReviewsController < Exposition::Admin::AdminController
  def index
    @book_reviews = BookReview.sorted_by_published_date.
      page(params[:page]).
      per(25)
  end

  def new
    @book_review = BookReview.new
    find_authors
    find_tags
  end

  def create
    @book_review = BookReview.new(book_review_params)
    if @book_review.save
      flash[:success] = "Review successfully created."
      redirect_to admin_book_reviews_path

    else
      find_authors
      find_tags
      render :new
    end
  end

  def edit
    find_book_review
    find_authors
    find_tags
  end

  def update
    find_book_review
    find_authors
    find_tags
    if @book_review.update(book_review_params)
      flash[:success] = "Book review was successfully updated."
      redirect_to admin_book_reviews_path
    else
      render action: 'edit'
    end
  end

  private

  def find_book_review
    @book_review = BookReview.find_by_slug!(params[:id])
  end

  def find_authors
    @authors = Exposition::User.all
  end

  def find_tags
    @tags = Categorical::Tag.all
  end

  def book_review_params
    params.require(:book_review).permit(:id, :book_title, :body, :slug, :published, :book_author, :image_url, :url, :author_id, tag_ids: [])
  end
end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Exposition::Admin::AdminController
  def index
    @tools = Tool.sorted_by_published_date.
      page(params[:page]).
      per(25)
  end

  def new
    @tool = Tool.new
    find_tags
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      flash[:success] = "Tool successfully created."
      redirect_to admin_tools_path

    else
      find_tags
      render :new
    end
  end

  def edit
    find_tool
    find_tags
  end

  def update
    find_tool
    find_tags
    if @tool.update(tool_params)
      flash[:success] = "Tool was successfully updated."
      redirect_to admin_tools_path
    else
      render action: 'edit'
    end
  end

  private

  def find_tool
    @tool = Tool.find_by_slug!(params[:id])
  end

  def find_tags
    @tags = Categorical::Tag.all
  end

  def tool_params
    params.require(:tool).permit(:id, :title, :body, :slug, :published, :url, tag_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'exposition/application'
  helper Exposition::Admin::FlashesHelper
end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  def index
    @book_reviews = BookReview.sorted_by_published_date.
      page(params[:page]).
      per(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
  layout 'exposition/application'
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Categorical::Tag.find_by_slug!(params[:id])
    @taggables = @tag.
      send(fetch_taggable_type).
      published.
      sorted_by_published_date.
      page(params[:page]).
      per(10)
  end

  private

  def fetch_taggable_type
    if params[:type]
      taggable_type = params[:type]
      return taggable_type.underscore.to_sym
    else
      return :posts
    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.sorted_by_published_date.
      page(params[:page]).
      per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
require 'redcarpet'
require 'rouge'
require 'rouge/plugins/redcarpet'

module MarkdownHelper

  # Create a Redcarpet Renderer with Rouge code formatting.
  # See: https://github.com/jneen/rouge#you-can-even-use-it-with-redcarpet
  class HTMLwithHighlighting < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end

  def markdown_to_html(markdown)
    @renderer ||=
      Redcarpet::Markdown.new(HTMLwithHighlighting,
                              extensions = {fenced_code_blocks: true})
    @renderer.render(markdown).html_safe
  end
end

app/helpers/tag_helper.rb
module TagHelper

  def display_tags_for(taggable)
    taggable_type = taggable.class.name.underscore.to_sym
    draw_tag_markup(tags: taggable.tags, taggable_type: taggable_type)
  end

  private

  def draw_tag_markup(tags:, taggable_type:)
    content_tag(:div, class: 'tags') do
      draw_tags(tags: tags, taggable_type: taggable_type)
    end
  end

  def draw_tags(tags:, taggable_type:)
    rendered_tags = ''

    if tags.any?
      tags.each do |tag|
        rendered_tags << content_tag(:span) do
          draw_tag_url(tag: tag, taggable_type: taggable_type)
        end
      end
    end

    return rendered_tags.html_safe
  end

  def draw_tag_url(tag:, taggable_type:)
    link_to(tag.label, exposition.tag_path(tag, type: taggable_type))
  end
end

app/views/admin/book_reviews/_form_fields.html.haml
%p
  = form.label :book_title
  = form.text_field :book_title
%p
  = form.label :book_author
  = form.text_field :book_author
%p
  = form.label :url
  = form.text_field :url
%p
  = form.label :image_url
  = form.text_field :image_url
%p
  = form.label :body
  = form.text_area :body
%p
  = form.label :author
  = form.collection_select(:author_id, @authors, :id, :name)
%p
  = form.label :slug
  = form.text_field :slug
%p
  = form.label :tag_ids, 'Tags'
  = form.collection_check_boxes(:tag_ids, @tags, :id, :label) do |b|
    = b.label { b.check_box + b.text }
%p
  = form.label :published
  = form.check_box :published
%p= form.submit

app/views/admin/book_reviews/edit.html.haml
%section.new-post
  .admin-title-header
    %h2 Edit Book Review
    = link_to "Back to Posts", admin_book_reviews_path
  = form_for @book_review, url: admin_book_review_path, method: :patch do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @book_review }
    = render partial: 'form_fields', locals: { form: f }

app/views/admin/book_reviews/index.html.haml
%section.posts
  .admin-title-header
    %h2 Book Reviews
    = link_to "Add New", new_admin_book_review_path
  %table 
    %thead
      %tr
        %th Title
        %th Article
        %th Author
        %th Slug
        %th Tags
        %th Manage
    %tbody
      - @book_reviews.each do |book_review|
        %tr.book_review{class: "#{book_review.css_classes}"}
          %td= "#{book_review.book_title}"
          %td= truncate(book_review.body, length: 40, separator: ' ')
          %td= "#{book_review.author.name}"
          %td= "#{book_review.slug}"
          %td= "#{book_review.tags.to_a.to_sentence}"
          %td= link_to "Edit", edit_admin_book_review_path(book_review)
  = paginate @book_reviews

app/views/admin/book_reviews/new.html.haml
%section.new-post
  .admin-title-header
    %h2 New Book Review
    = link_to "Back to Posts", admin_book_reviews_path
  = form_for @book_review, url: admin_book_reviews_path, method: :post do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @book_review }
    = render partial: 'form_fields', locals: { form: f }

app/views/admin/tools/_form_fields.html.haml
%p
  = form.label :title
  = form.text_field :title
%p
  = form.label :url
  = form.text_field :url
%p
  = form.label :body
  = form.text_area :body
%p
  = form.label :slug
  = form.text_field :slug
%p
  = form.label :tag_ids, 'Tags'
  = form.collection_check_boxes(:tag_ids, @tags, :id, :label) do |b|
    = b.label { b.check_box + b.text }
%p
  = form.label :published
  = form.check_box :published
%p= form.submit

app/views/admin/tools/edit.html.haml
%section.new-tool
  .admin-title-header
    %h2 Edit Tool
    = link_to "Back to Tools", admin_tools_path
  = form_for @tool, url: admin_tool_path, method: :patch do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @tool }
    = render partial: 'form_fields', locals: { form: f }

app/views/admin/tools/index.html.haml
%section.tools
  .admin-title-header
    %h2 Tools
    = link_to "Add New", new_admin_tool_path
  %table 
    %thead
      %tr
        %th Title
        %th Article
        %th Slug
        %th Tags
        %th Manage
    %tbody
      - @tools.each do |tool|
        %tr.tool{class: "#{tool.css_classes}"}
          %td= "#{tool.title}"
          %td= truncate(tool.body, length: 40, separator: ' ')
          %td= "#{tool.slug}"
          %td= "#{tool.tags.to_a.to_sentence}"
          %td= link_to "Edit", edit_admin_tool_path(tool)
  = paginate @tools

app/views/admin/tools/new.html.haml
%section.new-tool
  .admin-title-header
    %h2 New Tool
    = link_to "Back to Tools", admin_tools_path
  = form_for @tool, url: admin_tools_path, method: :post do |f|
    = render partial: 'exposition/admin/shared/error_handler', locals: { model: @tool }
    = render partial: 'form_fields', locals: { form: f }

app/views/book_reviews/_book_review.html.haml
%section.content
  %article.book-review
    %section.review
      %h2= book_review.book_title
      %p= book_review.body
    %section.info
      = display_tags_for(book_review)

app/views/book_reviews/index.html.haml
.book-reviews
  - unless @book_reviews.empty?
    = render @book_reviews
  -else
    %section.no-posts
      %p= t('book_reviews.index.no_reviews_warning')

  = paginate @book_reviews

app/views/exposition/posts/_post.html.haml
%article
  %time= "Published #{l(post.published_at.to_date, format: :long)}"
  .content.summary
    %h2= link_to(post.title, post)
    = preserve do
      = markdown_to_html(post.summary)
    %section.info
      = render 'exposition/posts/tags', tags: post.tags

app/views/layouts/exposition/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Exposition
    = stylesheet_link_tag    'exposition/admin/application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'exposition/admin/application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.admin
      %ul
        %li= link_to "Posts", exposition.admin_posts_path
        %li= link_to "Tags", exposition.admin_tags_path
        %li= link_to "Book Reviews", main_app.admin_book_reviews_path
        %li= link_to "Tools", main_app.admin_tools_path
      - if logged_in?
        %ul.login
          %li= link_to current_user.name, exposition.admin_posts_path
          %li= link_to t('sessions.destroy'), exposition.admin_logout_path, method: :delete
    - if flash.any?
      .flashes
        - user_facing_flashes.each do |key, value|
          %div{:class => "flash-#{key}"}= value
    = yield

app/views/layouts/exposition/application.html.haml
<!doctype html>
%html
  %head
    %title= content_for(:title) || t('title')
    %meta{"http-equiv" => "x-ua-compatible", content: "ie=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0"}
    %meta{charset: "utf-8"}
    %meta{name: "description", content: (content_for(:page_description) || t('page_description'))}
    %meta{name: "robots", content: "index,follow,noodp"}
    %meta{name: "generator", content: "Exposition"}
    %meta{name: "subject", content: t('site_subject')}
    %base{href: request.base_url}
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body
    %header
      %nav
        %h1= link_to t('title'), '/'
        %ul.social
          %li= link_to(image_tag('twitter.svg', class: 'twitter'), 'http://twitter.com/jj_klina', target: '_blank')
        %ul.menu
          %li= link_to 'Book Reviews', main_app.book_reviews_path
          %li= link_to 'Tools', main_app.tools_path
    = yield

    %footer
      .info
        %p= "By #{t('owner')}"

app/views/pages/tools.html.haml
%section.tools
  %h2 Tools
  %p A list of software and hardware that helps me get my work done. I'll try to post or update this list once a week. 

  %article.tool
    %h3= link_to('Quiver', 'http://happenapps.com/#quiver', target: '_blank')
    %p This is an OSX only notes app that I use everyday. Quiver supports Markdown, syncing, handles code well, and also has Vim key bindings. For taxonomies Quiver has a tagging system built in as well as Notebooks, which are basically folders you can place your notes in. There are options to export and even the ability to turn your documents into a quick presentation. As an original user of nvALT, Quiver adds all my wishlist features.
    %p= link_to("[link]", 'http://happenapps.com/#quiver', target: '_blank')

app/views/shared/_tags.html.haml
.tags
  - if tags.any?
    - tags.each do |tag|
      %span= link_to tag.label, tag
  - else
    %span.empty Not tagged

app/views/tags/show.html.haml
.posts
  - unless @taggables.empty?
    = render @taggables
  -else
    %section.no-taggables
      %p= t('taggables.show.no_taggables_warning')

app/views/tools/_tool.html.haml
%article.tool
  %h2= link_to(tool.title, tool.url, target: '_blank')
  .body
    %p= tool.body
    %p= link_to("[link]", tool.url, target: '_blank')

app/views/tools/index.html.haml
%section.tools
  .page-description
    %h2 Tools
    %p A list of software and hardware that helps me get my work done. I'll try to post or update this list once a week. 

  - unless @tools.empty?
    = render @tools
  -else
    %section.no-tools
      %p= t('tools.index.no_tools_warning')

  = paginate @tools